Repository passepartoutvpn/passepartout, pull requests merged in 2019-04, with the labels that each got.

#59 Integrate ProtonVPN provider
  CHANGELOG.md
  Passepartout-Core/Info.plist
  Passepartout-CoreTests/Info.plist
  Passepartout-iOS-Tunnel/Info.plist
  Passepartout-iOS/Global/SwiftGen+Assets.swift
  Passepartout-iOS/Info.plist
  Passepartout-iOS/Providers.xcassets/protonvpn.imageset/Contents.json
  Passepartout-iOS/Providers.xcassets/protonvpn.imageset/protonvpn@2x.png
  Passepartout-iOS/Providers.xcassets/protonvpn.imageset/protonvpn@3x.png
  Passepartout-iOS/Scenes/AccountViewController.swift
  Passepartout/Resources/Web/net/protonvpn.json
  Passepartout/Resources/en.lproj/Localizable.strings
  Passepartout/Sources/AppConstants.swift
  Passepartout/Sources/Services/Infrastructure.swift
  Passepartout/Sources/Services/InfrastructureFactory.swift
  Passepartout/Sources/SwiftGen+Strings.swift
  README.md
  fastlane/metadata/en-US/description.txt
Labels: enhancement

#61 Default "Automatic" protocol to UDP
  CHANGELOG.md
  Passepartout/Resources/en.lproj/Localizable.strings
  Passepartout/Resources/it.lproj/Localizable.strings
  Passepartout/Sources/Model/Profiles/ProviderConnectionProfile.swift
  Passepartout/Sources/SwiftGen+Strings.swift
Labels: bug

#65 Integrate NordVPN
  CHANGELOG.md
  Passepartout-iOS/Global/SwiftGen+Assets.swift
  Passepartout-iOS/Providers.xcassets/nordvpn.imageset/Contents.json
  Passepartout-iOS/Providers.xcassets/nordvpn.imageset/nordvpn@2x.png
  Passepartout-iOS/Providers.xcassets/nordvpn.imageset/nordvpn@3x.png
  Passepartout-iOS/Scenes/AccountViewController.swift
  Passepartout.xcodeproj/project.pbxproj
  Passepartout/Resources/Web/net/nordvpn.json
  Passepartout/Resources/en.lproj/Localizable.strings
  Passepartout/Sources/AppConstants.swift
  Passepartout/Sources/Model/ConnectionService.swift
  Passepartout/Sources/Model/Profiles/ProviderConnectionProfile.swift
  Passepartout/Sources/Services/Infrastructure.swift
  Passepartout/Sources/Services/InfrastructureFactory.swift
  Passepartout/Sources/Services/Pool.swift
  Passepartout/Sources/SwiftGen+Strings.swift
  Podfile
  Podfile.lock
  README.md
  fastlane/metadata/en-US/description.txt
Labels: enhancement

#70 Add pt-br translation
  Passepartout/Resources/en.lproj/Localizable.strings
  Passepartout/Resources/pt-br.lproj/Intents.strings
  Passepartout/Resources/pt-br.lproj/Localizable.strings
Labels: enhancement

#71 Do not imply default gateway
  CHANGELOG.md
  Passepartout-iOS/Scenes/ConfigurationViewController.swift
  Passepartout/Resources/en.lproj/Localizable.strings
  Passepartout/Sources/Model/ConnectionService.swift
  Passepartout/Sources/Model/TransientStore.swift
  Passepartout/Sources/Services/InfrastructurePreset.swift
  Passepartout/Sources/SwiftGen+Strings.swift
  Podfile
  Podfile.lock
Labels: bug, enhancement

#72 Integrate VyprVPN
  Passepartout-iOS/Providers.xcassets/vyprvpn.imageset/Contents.json
  Passepartout-iOS/Providers.xcassets/vyprvpn.imageset/vyprvpn@2x.png
  Passepartout-iOS/Providers.xcassets/vyprvpn.imageset/vyprvpn@3x.png
  Passepartout-iOS/Scenes/AccountViewController.swift
  Passepartout/Resources/Web/net/vyprvpn.json
  Passepartout/Resources/de.lproj/Localizable.strings
  Passepartout/Resources/en.lproj/Localizable.strings
  Passepartout/Resources/it.lproj/Localizable.strings
  Passepartout/Resources/pt-br.lproj/Localizable.strings
  Passepartout/Resources/ru.lproj/Localizable.strings
  Passepartout/Sources/Services/Infrastructure.swift
  Passepartout/Sources/Services/InfrastructureFactory.swift
  Passepartout/Sources/SwiftGen+Strings.swift
Labels: enhancement

#76 Update Localizable.strings
  Passepartout/Resources/de.lproj/Localizable.strings
Labels: bug
