Repository passepartoutvpn/passepartout, pull requests merged in 2023-04, with the labels that each got.

#276 Force Mac "Catalyst" idiom in debug log
  PassepartoutLibrary/Sources/PassepartoutLibrary/Extensions/DebugLog+Extensions.swift
Labels: bug

#277 Use a distinct debug log per VPN protocol
  PassepartoutLibrary/Sources/PassepartoutVPN/Extensions/OpenVPNSettings+VPNConfiguration.swift
  PassepartoutLibrary/Sources/PassepartoutVPN/Extensions/VPNProtocolType+Extensions.swift
  PassepartoutLibrary/Sources/PassepartoutVPN/Extensions/WireGuardSettings+VPNConfiguration.swift
Labels: bug

#278 Always show "Reconnect" button
  CHANGELOG.md
  Passepartout/App/Views/OrganizerView+Profiles.swift
  Passepartout/App/Views/ProfileView+MainMenu.swift
Labels: enhancement

#279 Catch WireGuard parsing errors properly
  Passepartout.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Passepartout/AppShared/L10n/TunnelKit+L10n.swift
  PassepartoutLibrary/Package.swift
  PassepartoutLibrary/Sources/PassepartoutProfiles/Managers/ProfileManager+Processing.swift
Labels: bug

#280 Import missing translations
  Passepartout.xcodeproj/project.pbxproj
  Passepartout/App/Intents/ua.lproj/Intents.strings
  Passepartout/App/Intents/uk.lproj/Intents.strings
  Passepartout/App/Views/AccountView.swift
  Passepartout/App/de.lproj/InfoPlist.strings
  Passepartout/App/el.lproj/InfoPlist.strings
  Passepartout/App/es.lproj/InfoPlist.strings
  Passepartout/App/fr.lproj/InfoPlist.strings
  Passepartout/App/it.lproj/InfoPlist.strings
  Passepartout/App/nl.lproj/InfoPlist.strings
  Passepartout/App/pl.lproj/InfoPlist.strings
  Passepartout/App/pt.lproj/InfoPlist.strings
  Passepartout/App/ru.lproj/InfoPlist.strings
  Passepartout/App/sv.lproj/InfoPlist.strings
  Passepartout/App/ua.lproj/InfoPlist.strings
  Passepartout/App/uk.lproj/InfoPlist.strings
  Passepartout/App/zh-Hans.lproj/InfoPlist.strings
  Passepartout/AppShared/Constants/SwiftGen+Strings.swift
  Passepartout/AppShared/de.lproj/Localizable.strings
  Passepartout/AppShared/el.lproj/Localizable.strings
  Passepartout/AppShared/en.lproj/Localizable.strings
  Passepartout/AppShared/es.lproj/Localizable.strings
  Passepartout/AppShared/fr.lproj/Localizable.strings
  Passepartout/AppShared/it.lproj/Localizable.strings
  Passepartout/AppShared/nl.lproj/Localizable.strings
  Passepartout/AppShared/pl.lproj/Localizable.strings
  Passepartout/AppShared/pt.lproj/Localizable.strings
  Passepartout/AppShared/ru.lproj/Localizable.strings
  Passepartout/AppShared/sv.lproj/Localizable.strings
  Passepartout/AppShared/ua.lproj/Localizable.strings
  Passepartout/AppShared/uk.lproj/Localizable.strings
  Passepartout/AppShared/zh-Hans.lproj/Localizable.strings
  PassepartoutLibrary/.swiftpm/xcode/xcshareddata/xcschemes/OpenVPNAppExtension.xcscheme
  PassepartoutLibrary/.swiftpm/xcode/xcshareddata/xcschemes/PassepartoutLibrary.xcscheme
  PassepartoutLibrary/.swiftpm/xcode/xcshareddata/xcschemes/PassepartoutProvidersTests.xcscheme
  PassepartoutLibrary/.swiftpm/xcode/xcshareddata/xcschemes/PassepartoutServicesTests.xcscheme
  PassepartoutLibrary/.swiftpm/xcode/xcshareddata/xcschemes/PassepartoutUtilsTests.xcscheme
  PassepartoutLibrary/.swiftpm/xcode/xcshareddata/xcschemes/WireGuardAppExtension.xcscheme
Labels: bug

#281 Recognize IAPs other than full version on Mac
  CHANGELOG.md
  Passepartout/App/InApp/ProductManager.swift
Labels: bug, regression, macOS

#282 Cover screen on .inactive
  CHANGELOG.md
  Passepartout/App/Constants/Theme.swift
  Passepartout/App/Reusable/LockableView.swift
Labels: enhancement

#283 Override manual DNS servers when using DoH/DoT
  PassepartoutLibrary/Sources/PassepartoutVPN/Extensions/WireGuardSettings+VPNConfiguration.swift
Labels: bug

#284 Address issues with release notes in workflow
  .env.ios
  .env.mac
  .github/workflows/test.yml
  ci/latest-changelog.sh
  ci/update-release-notes.sh
  scripts/ci/release-notes.sh
Labels: bug

#285 Remove nonsense Mac menus
  Passepartout/App/AppDelegate.swift
Labels: bug, macOS

#286 Show app version in Mac menu
  Passepartout/Mac/Menu/PassepartoutMenu.swift
Labels: enhancement, macOS

#288 Small fixes for Ukrainian translation
  Passepartout/AppShared/uk.lproj/Localizable.strings
Labels: bug

#294 Roll back broken TunnelKit .killSwitch flag
  CHANGELOG.md
  PassepartoutLibrary/Sources/PassepartoutVPN/Extensions/OpenVPNSettings+VPNConfiguration.swift
  PassepartoutLibrary/Sources/PassepartoutVPN/Extensions/WireGuardSettings+VPNConfiguration.swift
Labels: bug, regression
