Repository passepartoutvpn/passepartout, pull requests merged in 2024-11, with the labels that each got.

#794 Revisit overuse of EnvironmentObject
  Passepartout/App/Platforms/App+macOS.swift
  Passepartout/Library/Sources/AppUI/Business/AppContext.swift
  Passepartout/Library/Sources/AppUI/Business/ExtendedTunnel.swift
  Passepartout/Library/Sources/AppUI/Business/InteractiveManager.swift
  Passepartout/Library/Sources/AppUI/Extensions/Tunnel+Extensions.swift
  Passepartout/Library/Sources/AppUI/Extensions/View+Environment.swift
  Passepartout/Library/Sources/AppUI/Mock/Mock.swift
  Passepartout/Library/Sources/AppUI/Protocols/AppCoordinatorConforming.swift
  Passepartout/Library/Sources/AppUI/Protocols/TunnelInstallationProviding.swift
  Passepartout/Library/Sources/AppUI/UI/ConnectionStatusView.swift
  Passepartout/Library/Sources/AppUI/UI/ExtendedTunnel+Theme.swift
  Passepartout/Library/Sources/AppUI/UI/TunnelToggleButton.swift
  Passepartout/Library/Sources/AppUIMain/Domain/Issue+Metadata.swift
  Passepartout/Library/Sources/AppUIMain/UI/InstalledProfileView.swift
  Passepartout/Library/Sources/AppUIMain/UI/ProfileContextMenu.swift
  Passepartout/Library/Sources/AppUIMain/UI/ProfileRowView.swift
  Passepartout/Library/Sources/AppUIMain/UI/TunnelContextProviding+Theme.swift
  Passepartout/Library/Sources/AppUIMain/UI/TunnelRestartButton.swift
  Passepartout/Library/Sources/AppUIMain/Views/About/AboutRouterView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/AppCoordinator.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileContainerView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileGridView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileListView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProviderEntitySelector.swift
  Passepartout/Library/Sources/AppUIMain/Views/AppMenu/macOS/AppMenu.swift
  Passepartout/Library/Sources/AppUIMain/Views/AppMenu/macOS/AppMenuImage.swift
  Passepartout/Library/Sources/AppUIMain/Views/Diagnostics/DebugLogView.swift
  Passepartout/Library/Sources/AppUIMain/Views/Diagnostics/DiagnosticsView.swift
  Passepartout/Library/Sources/AppUIMain/Views/Diagnostics/ReportIssueButton.swift
  Passepartout/Library/Sources/AppUIMain/Views/Provider/ProviderContentModifier.swift
  Passepartout/Library/Sources/AppUITV/Views/AppCoordinator.swift
  Passepartout/Library/Tests/AppUITests/ExtendedTunnelTests.swift
Labels: bug, refactoring

#796 Allow interactive credentials with providers
  Passepartout.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Passepartout/Library/Package.swift
  Passepartout/Library/Sources/AppUI/L10n/AppError+L10n.swift
  Passepartout/Library/Sources/AppUI/L10n/SwiftGen+Strings.swift
  Passepartout/Library/Sources/AppUI/Resources/en.lproj/Localizable.strings
  Passepartout/Library/Tests/AppUITests/ExtendedTunnelTests.swift
Labels: bug

#798 Create basic UI for TV app
  Passepartout.xcodeproj/project.pbxproj
  Passepartout/Library/Package.swift
  Passepartout/Library/Sources/AppLibrary/Business/ExtendedTunnel.swift
  Passepartout/Library/Sources/AppUI/L10n/SwiftGen+Strings.swift
  Passepartout/Library/Sources/AppUI/Resources/en.lproj/Localizable.strings
  Passepartout/Library/Sources/AppUI/Theme/Platforms/Theme+iOS.swift
  Passepartout/Library/Sources/AppUI/Theme/Platforms/Theme+macOS.swift
  Passepartout/Library/Sources/AppUI/Theme/Platforms/Theme+tvOS.swift
  Passepartout/Library/Sources/AppUI/Theme/Theme+ImageName.swift
  Passepartout/Library/Sources/AppUI/Theme/UI/Theme+Views.swift
  Passepartout/Library/Sources/AppUI/Views/UI/ConnectionStatusText.swift
  Passepartout/Library/Sources/AppUI/Views/UI/TunnelToggleButton.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/InstalledProfileView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileRowView.swift
  Passepartout/Library/Sources/AppUIMain/Views/Provider/VPNFiltersView.swift
  Passepartout/Library/Sources/AppUIMain/Views/Provider/iOS/VPNProviderServerView+iOS.swift
  Passepartout/Library/Sources/AppUIMain/Views/Provider/macOS/VPNProviderServerView+macOS.swift
  Passepartout/Library/Sources/AppUIPlatform/Dummy.swift
  Passepartout/Library/Sources/AppUITV/Views/App/AppCoordinator.swift
  Passepartout/Library/Sources/AppUITV/Views/Profile/ActiveProfileView.swift
  Passepartout/Library/Sources/AppUITV/Views/Profile/ProfileListView.swift
  Passepartout/Library/Sources/AppUITV/Views/Profile/ProfileView.swift
Labels: enhancement, refactoring, tvOS

#800 Refactor ModuleType to be a single source of truth
  Passepartout/Library/Sources/AppUIMain/Protocols/DefaultModuleViewFactory.swift
  Passepartout/Library/Sources/AppUIMain/Views/Modules/OpenVPNView.swift
  Passepartout/Library/Sources/AppUIMain/Views/Profile/ModuleViewModifier.swift
  Passepartout/Library/Sources/AppUIMain/Views/Profile/ProfileCoordinator.swift
  Passepartout/Library/Sources/UILibrary/Business/ProfileEditor.swift
  Passepartout/Library/Sources/UILibrary/Domain/Module+ModuleType.swift
  Passepartout/Library/Sources/UILibrary/Domain/ModuleType+Known.swift
  Passepartout/Library/Sources/UILibrary/Domain/ModuleType+New.swift
  Passepartout/Library/Sources/UILibrary/Domain/ModuleType.swift
  Passepartout/Library/Sources/UILibrary/L10n/AppError+L10n.swift
  Passepartout/Library/Sources/UILibrary/L10n/ModuleBuilder+Description.swift
  Passepartout/Library/Sources/UILibrary/L10n/ModuleType+L10n.swift
  Passepartout/Library/Sources/UILibrary/UILibrary.swift
Labels: bug

#801 Refactor and improve interactive login
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileContainerView.swift
  Passepartout/Library/Sources/AppUIMain/Views/Modules/OpenVPNView.swift
  Passepartout/Library/Sources/AppUIMain/Views/Profile/iOS/ProfileEditView+iOS.swift
  Passepartout/Library/Sources/AppUITV/Views/App/AppCoordinator.swift
  Passepartout/Library/Sources/AppUITV/Views/Profile/ProfileListView.swift
  Passepartout/Library/Sources/AppUITV/Views/Profile/ProfileView.swift
  Passepartout/Library/Sources/UILibrary/L10n/SwiftGen+Strings.swift
  Passepartout/Library/Sources/UILibrary/Resources/en.lproj/Localizable.strings
  Passepartout/Library/Sources/UILibrary/Theme/Platforms/Theme+tvOS.swift
  Passepartout/Library/Sources/UILibrary/Views/Modules/OpenVPNView+Credentials.swift
  Passepartout/Library/Sources/UILibrary/Views/UI/InteractiveCoordinator.swift
  Passepartout/Library/Sources/UILibrary/Views/UI/InteractiveView.swift
  swiftgen.yml
Labels: enhancement, refactoring, tvOS

#802 Resolve some focus issues
  Passepartout/Library/Sources/AppUITV/Views/Profile/ActiveProfileView.swift
  Passepartout/Library/Sources/AppUITV/Views/Profile/ProfileView.swift
  Passepartout/Library/Sources/UILibrary/Views/Modules/OpenVPNView+Credentials.swift
Labels: bug, tvOS

#803 Fix flashing context menu on data count update
  Passepartout/Library/Sources/AppUIMain/Views/App/InstalledProfileView.swift
Labels: bug

#804 Late dismissal after changing active provider server
  Passepartout/Library/Sources/AppUIMain/Extensions/ProviderEntityViewProviding+Extensions.swift
  Passepartout/Library/Sources/AppUIMain/Protocols/ProviderEntityViewProviding.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/AppCoordinator.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileContainerView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProviderEntitySelector.swift
  Passepartout/Library/Sources/AppUIMain/Views/Modules/Extensions/OpenVPNModule+Extensions.swift
  Passepartout/Library/Sources/AppUIMain/Views/Provider/VPNProviderServerCoordinator.swift
Labels: bug

#805 Submit on OpenVPN fields
  Passepartout/Library/Sources/UILibrary/Protocols/InteractiveViewProviding.swift
  Passepartout/Library/Sources/UILibrary/Views/Modules/Extensions/OpenVPNModule+Extensions.swift
  Passepartout/Library/Sources/UILibrary/Views/Modules/OpenVPNView+Credentials.swift
  Passepartout/Library/Sources/UILibrary/Views/UI/InteractiveCoordinator.swift
Labels: enhancement, tvOS

#807 Fine-tune profile management with additional attributes
  Passepartout.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Passepartout/Library/Package.swift
  Passepartout/Library/Sources/AppDataProfiles/CDProfileRepositoryV3.swift
  Passepartout/Library/Sources/AppDataProfiles/Domain/CDProfileV3.swift
  Passepartout/Library/Sources/AppDataProfiles/Profiles.xcdatamodeld/ProfilesV3.xcdatamodel/contents
  Passepartout/Library/Sources/AppUIMain/Views/App/AppCoordinator.swift
  Passepartout/Library/Sources/CommonLibrary/Business/InMemoryProfileRepository.swift
  Passepartout/Library/Sources/CommonLibrary/Business/NEProfileRepository.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileManager.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProviderFavoritesManager.swift
  Passepartout/Library/Sources/CommonLibrary/Domain/ProfileAttributes.swift
  Passepartout/Library/Sources/CommonLibrary/Domain/ProviderFavoriteServers.swift
  Passepartout/Library/Sources/CommonUtils/Business/CoreDataRepository.swift
  Passepartout/Library/Sources/UILibrary/Domain/EditableProfile.swift
  Passepartout/Library/Tests/UILibraryTests/ProfileEditorTests.swift
Labels: bug, refactoring

#808 Implement TV profile sharing
  Passepartout/Library/Sources/AppDataProfiles/CDProfileRepositoryV3.swift
  Passepartout/Library/Sources/AppDataProfiles/Domain/CDProfileV3.swift
  Passepartout/Library/Sources/AppDataProfiles/Profiles.xcdatamodeld/ProfilesV3.xcdatamodel/contents
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileRowView.swift
  Passepartout/Library/Sources/AppUIMain/Views/Profile/StorageSection.swift
  Passepartout/Library/Sources/AppUITV/Views/Profile/ProfileListView.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileManager.swift
  Passepartout/Library/Sources/CommonLibrary/Domain/ProfileAttributes.swift
  Passepartout/Library/Sources/UILibrary/Business/ProfileEditor.swift
  Passepartout/Library/Sources/UILibrary/L10n/Strings+Unlocalized.swift
  Passepartout/Library/Sources/UILibrary/L10n/SwiftGen+Strings.swift
  Passepartout/Library/Sources/UILibrary/Resources/en.lproj/Localizable.strings
  Passepartout/Library/Sources/UILibrary/Theme/Theme+ImageName.swift
  Passepartout/Shared/Shared+App.swift
Labels: enhancement, tvOS

#809 Review ProfileManager observation logic
  Passepartout/App/Platforms/App+iOS.swift
  Passepartout/App/Platforms/App+macOS.swift
  Passepartout/Library/Sources/AppUIMain/AppUIMain.swift
  Passepartout/Library/Sources/CommonLibrary/Business/NEProfileRepository.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileManager.swift
  Passepartout/Library/Sources/CommonLibrary/Domain/ProfileAttributes.swift
  Passepartout/Library/Sources/UILibrary/Business/ProfileEditor.swift
  Passepartout/Library/Sources/UILibrary/UILibrary.swift
Labels: bug, refactoring

#810 Refactor AppContext creation and profile processing
  Passepartout/App/Platforms/App+macOS.swift
  Passepartout/Library/Sources/AppDataProfiles/CDProfileRepositoryV3.swift
  Passepartout/Library/Sources/AppUIMain/Views/About/CreditsView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProviderEntitySelector.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/TunnelRestartButton.swift
  Passepartout/Library/Sources/AppUIMain/Views/AppMenu/macOS/AppMenu.swift
  Passepartout/Library/Sources/AppUIMain/Views/Profile/ProfileSaveButton.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ExtendedTunnel.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileManager.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileProcessor.swift
  Passepartout/Library/Sources/CommonLibrary/Domain/AppError.swift
  Passepartout/Library/Sources/CommonLibrary/Domain/ProfileAttributes.swift
  Passepartout/Library/Sources/CommonUtils/Business/BuildProducts.swift
  Passepartout/Library/Sources/UILibrary/Business/AppContext.swift
  Passepartout/Library/Sources/UILibrary/Extensions/View+Environment.swift
  Passepartout/Library/Sources/UILibrary/L10n/AppError+L10n.swift
  Passepartout/Library/Sources/UILibrary/L10n/ErrorHandler+Default.swift
  Passepartout/Library/Sources/UILibrary/Mock/AppContext+Mock.swift
  Passepartout/Library/Sources/UILibrary/Mock/Profile+Mock.swift
  Passepartout/Library/Sources/UILibrary/Views/UI/ConnectionStatusText.swift
  Passepartout/Library/Sources/UILibrary/Views/UI/TunnelToggleButton.swift
  Passepartout/Shared/Shared+App.swift
Labels: refactoring

#812 Encapsulate behavior on app active
  Passepartout.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Passepartout/App/PassepartoutApp.swift
  Passepartout/Library/Package.swift
  Passepartout/Library/Sources/AppUIMain/AppUIMain.swift
  Passepartout/Library/Sources/AppUIMain/Views/Provider/VPNFiltersView+Model.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ExtendedTunnel.swift
  Passepartout/Library/Sources/UILibrary/Business/AppContext.swift
  Passepartout/Library/Sources/UILibrary/UILibrary.swift
  Passepartout/Library/Tests/CommonLibraryTests/ExtendedTunnelTests.swift
Labels: refactoring

#813 Persist "Only favorites" toggle
  Passepartout/Library/Sources/AppUIMain/Views/Provider/VPNFiltersView+Model.swift
  Passepartout/Library/Sources/AppUIMain/Views/Provider/VPNProviderServerView.swift
  Passepartout/Library/Sources/CommonLibrary/Domain/AppPreference.swift
Labels: enhancement, refactoring

#814 Improve footers in macOS form sections
  Passepartout/Library/Sources/AppUIMain/Views/Modules/OnDemandView.swift
  Passepartout/Library/Sources/AppUIMain/Views/Profile/AppleTVSection.swift
  Passepartout/Library/Sources/AppUIMain/Views/Profile/StorageSection.swift
  Passepartout/Library/Sources/AppUIMain/Views/Settings/SettingsSectionGroup.swift
  Passepartout/Library/Sources/UILibrary/Theme/Platforms/Theme+iOS.swift
  Passepartout/Library/Sources/UILibrary/Theme/Platforms/Theme+macOS.swift
  Passepartout/Library/Sources/UILibrary/Theme/Platforms/Theme+tvOS.swift
  Passepartout/Library/Sources/UILibrary/Theme/UI/Theme+Modifiers.swift
  Passepartout/Library/Sources/UILibrary/Views/Modules/OpenVPNView+Credentials.swift
Labels: enhancement, macOS

#816 Address some issues with animations
  Passepartout/Library/Sources/AppUIMain/Views/Modules/OpenVPNView.swift
  Passepartout/Library/Sources/AppUITV/Views/Profile/ProfileView.swift
  Passepartout/Library/Sources/UILibrary/Theme/UI/Theme+Modifiers.swift
Labels: bug, refactoring

#817 TV not presenting interactive login on "Connect"
  Passepartout/Library/Sources/AppUITV/Views/Profile/ProfileView.swift
Labels: bug, tvOS

#821 Improve configuration on app launch/active
  Passepartout.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Passepartout/App/AppDelegate.swift
  Passepartout/App/Platforms/App+iOS.swift
  Passepartout/App/Platforms/App+macOS.swift
  Passepartout/Library/Package.swift
  Passepartout/Library/Sources/AppDataProfiles/CDProfileRepositoryV3.swift
  Passepartout/Library/Sources/AppUIMain/AppUIMain.swift
  Passepartout/Library/Sources/AppUITV/AppUITV.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileManager.swift
  Passepartout/Library/Sources/CommonLibrary/IAP/IAPManager.swift
  Passepartout/Library/Sources/CommonUtils/Business/CoreDataRepository.swift
  Passepartout/Library/Sources/UILibrary/Business/AppContext.swift
  Passepartout/Library/Sources/UILibrary/UILibrary.swift
Labels: bug, enhancement

#822 Improve startup time
  Passepartout/Library/Sources/CommonLibrary/Business/ExtendedTunnel.swift
  Passepartout/Library/Sources/UILibrary/Business/AppContext.swift
Labels: regression

#824 Read receipts in a serial fashion
  Passepartout/Library/Sources/CommonLibrary/IAP/FallbackReceiptReader.swift
  Passepartout/Library/Sources/CommonLibrary/IAP/IAPManager.swift
  Passepartout/Library/Sources/CommonLibrary/Shared.swift
Labels: bug

#825 Fine-tune important logging categories
  Passepartout/Library/Sources/CommonLibrary/Business/InMemoryProfileRepository.swift
  Passepartout/Library/Sources/CommonLibrary/Business/NEProfileRepository.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileManager.swift
  Passepartout/Library/Sources/CommonLibrary/Domain/ProfileAttributes.swift
  Passepartout/Library/Sources/CommonLibrary/IAP/FallbackReceiptReader.swift
  Passepartout/Library/Sources/CommonLibrary/IAP/IAPManager.swift
  Passepartout/Library/Sources/CommonLibrary/Shared.swift
Labels: refactoring

#826 Always read local receipt in TestFlight
  Passepartout/Library/Sources/CommonLibrary/IAP/FallbackReceiptReader.swift
Labels: bug, macOS

#827 Erase shared profiles from iCloud correctly
  Passepartout/Library/Sources/AppDataProfiles/CDProfileRepositoryV3.swift
  Passepartout/Library/Sources/AppUIMain/Views/Settings/SettingsSectionGroup.swift
  Passepartout/Library/Sources/CommonLibrary/Business/InMemoryProfileRepository.swift
  Passepartout/Library/Sources/CommonLibrary/Business/NEProfileRepository.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileManager.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileRepository.swift
  Passepartout/Library/Sources/CommonUtils/Business/CoreDataRepository.swift
  Passepartout/Library/Sources/CommonUtils/Business/Repository.swift
Labels: bug

#828 Fix missing profile attributes initialization
  Passepartout/Library/Sources/CommonLibrary/Business/NEProfileRepository.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileManager.swift
  Passepartout/Library/Sources/CommonLibrary/Domain/ProfileAttributes.swift
Labels: bug, refactoring

#829 Refactor theme section and styles
  Passepartout/Library/Sources/AppUIMain/Views/Modules/OnDemandView.swift
  Passepartout/Library/Sources/AppUIMain/Views/Profile/AppleTVSection.swift
  Passepartout/Library/Sources/AppUIMain/Views/Profile/StorageSection.swift
  Passepartout/Library/Sources/AppUIMain/Views/Provider/iOS/VPNProviderServerView+iOS.swift
  Passepartout/Library/Sources/AppUIMain/Views/Settings/SettingsSectionGroup.swift
  Passepartout/Library/Sources/AppUITV/Views/Profile/ProfileListView.swift
  Passepartout/Library/Sources/UILibrary/L10n/SwiftGen+Strings.swift
  Passepartout/Library/Sources/UILibrary/Resources/en.lproj/Localizable.strings
  Passepartout/Library/Sources/UILibrary/Theme/UI/Theme+Modifiers.swift
Labels: enhancement, refactoring

#837 Revisit in-app eligibility for iCloud sharing
  Passepartout.xcodeproj/project.pbxproj
  Passepartout.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Passepartout/Library/Package.swift
  Passepartout/Library/Sources/AppDataProfiles/CDProfileRepositoryV3.swift
  Passepartout/Library/Sources/AppDataProfiles/Domain/CDProfileV3.swift
  Passepartout/Library/Sources/AppDataProfiles/Profiles.xcdatamodeld/ProfilesV3.xcdatamodel/contents
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileRowView.swift
  Passepartout/Library/Sources/AppUIMain/Views/Profile/AppleTVSection.swift
  Passepartout/Library/Sources/AppUIMain/Views/Profile/StorageSection.swift
  Passepartout/Library/Sources/AppUIMain/Views/Profile/iOS/ProfileEditView+iOS.swift
  Passepartout/Library/Sources/AppUIMain/Views/Profile/macOS/ProfileGeneralView+macOS.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileManager.swift
  Passepartout/Library/Sources/CommonLibrary/Domain/AppError.swift
  Passepartout/Library/Sources/CommonLibrary/Domain/Constants.swift
  Passepartout/Library/Sources/CommonLibrary/Domain/ProfileAttributes.swift
  Passepartout/Library/Sources/CommonLibrary/IAP/AppFeature.swift
  Passepartout/Library/Sources/CommonLibrary/IAP/AppFeatureProviding.swift
  Passepartout/Library/Sources/CommonLibrary/IAP/AppProduct+Features.swift
  Passepartout/Library/Sources/CommonLibrary/IAP/IAPManager.swift
  Passepartout/Library/Sources/CommonLibrary/Resources/Constants.json
  Passepartout/Library/Sources/CommonUtils/Business/CoreDataRepository.swift
  Passepartout/Library/Sources/UILibrary/Business/AppContext.swift
  Passepartout/Library/Sources/UILibrary/Business/ProfileEditor.swift
  Passepartout/Library/Sources/UILibrary/L10n/AppError+L10n.swift
  Passepartout/Library/Sources/UILibrary/L10n/AppFeature+L10n.swift
  Passepartout/Library/Sources/UILibrary/L10n/SwiftGen+Strings.swift
  Passepartout/Library/Sources/UILibrary/Mock/AppContext+Mock.swift
  Passepartout/Library/Sources/UILibrary/Resources/en.lproj/Localizable.strings
  Passepartout/Library/Sources/UILibrary/Theme/Theme+ImageName.swift
  Passepartout/Library/Sources/UILibrary/Views/Modules/OpenVPNView+Credentials.swift
  Passepartout/Library/Sources/UILibrary/Views/Paywall/PaywallView.swift
  Passepartout/Library/Tests/CommonLibraryTests/IAPManagerTests.swift
  Passepartout/Shared/AppContext+Shared.swift
  Passepartout/Shared/Shared+App.swift
  Passepartout/Shared/Shared.swift
  Passepartout/Tunnel/PacketTunnelProvider.swift
Labels: bug, refactoring, tvOS

#838 Add more view modifiers
  Passepartout/Library/Sources/AppUIMain/Views/About/DonateView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/InstalledProfileView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileContainerView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileRowView.swift
  Passepartout/Library/Sources/AppUIMain/Views/Provider/iOS/VPNProviderServerView+iOS.swift
  Passepartout/Library/Sources/AppUIMain/Views/Provider/macOS/VPNProviderServerView+macOS.swift
  Passepartout/Library/Sources/AppUITV/Views/Profile/ProfileView.swift
  Passepartout/Library/Sources/CommonUtils/Views/View+Extensions.swift
  Passepartout/Library/Sources/UILibrary/Theme/UI/Theme+Modifiers.swift
  Passepartout/Library/Sources/UILibrary/Theme/UI/Theme+Views.swift
  Passepartout/Library/Sources/UILibrary/Views/Paywall/PaywallView.swift
  Passepartout/Library/Sources/UILibrary/Views/UI/FavoriteToggle.swift
Labels: enhancement, refactoring

#839 Rewrite AppContext event handlers
  Passepartout.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Passepartout/App/AppDelegate.swift
  Passepartout/Library/Package.swift
  Passepartout/Library/Sources/AppDataProfiles/CDProfileRepositoryV3.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ExtendedTunnel.swift
  Passepartout/Library/Sources/CommonLibrary/Business/InMemoryProfileRepository.swift
  Passepartout/Library/Sources/CommonLibrary/Business/NEProfileRepository.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileManager.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileRepository.swift
  Passepartout/Library/Sources/CommonLibrary/Domain/AppError.swift
  Passepartout/Library/Sources/CommonLibrary/IAP/IAPManager.swift
  Passepartout/Library/Sources/CommonUtils/Business/CoreDataRepository.swift
  Passepartout/Library/Sources/CommonUtils/IAP/StoreKitHelper.swift
  Passepartout/Library/Sources/UILibrary/Business/AppContext.swift
  Passepartout/Library/Sources/UILibrary/L10n/AppError+L10n.swift
Labels: bug, refactoring

#841 Fix regression about handling of Core Data duplicates
  Passepartout/Library/Sources/CommonUtils/Business/CoreDataRepository.swift
Labels: regression

#844 Use hidden icons for stable alignment
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileAttributesView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileRowView.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileManager.swift
Labels: bug

#846 fix: make few small fixes for ukranian translation
  Passepartout/App/L10n/Unlocalized.swift
  Passepartout/App/uk.lproj/Localizable.strings
Labels: bug

#847 Wait for initial profiles
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileContainerView.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileManager.swift
Labels: enhancement

#848 React on providers eligibility
  Passepartout/Library/Sources/CommonLibrary/IAP/AppFeature.swift
  Passepartout/Library/Sources/CommonLibrary/IAP/AppProduct.swift
  Passepartout/Library/Sources/UILibrary/Business/AppContext.swift
  Passepartout/Tunnel/PacketTunnelProvider.swift
Labels: bug

#852 Exclude interactive login from v2
  Passepartout/Library/Sources/CommonLibrary/IAP/AppFeature.swift
  Passepartout/Library/Sources/CommonLibrary/IAP/AppFeatureProviding.swift
  Passepartout/Library/Sources/CommonLibrary/IAP/AppUserLevel.swift
  Passepartout/Library/Tests/CommonLibraryTests/IAPManagerTests.swift
Labels: refactoring

#853 Expand selected server country on iOS
  Passepartout/Library/Sources/AppUIMain/Views/Provider/VPNProviderServerView.swift
  Passepartout/Library/Sources/AppUIMain/Views/Provider/iOS/VPNProviderServerView+iOS.swift
  Passepartout/Library/Sources/AppUIMain/Views/Provider/macOS/VPNProviderServerView+macOS.swift
Labels: enhancement, iOS

#855 Split test jobs
  .github/workflows/release.yml
  .github/workflows/test.yml
  Passepartout.xcodeproj/project.pbxproj
  Passepartout.xcodeproj/xcshareddata/xcschemes/Passepartout.xcscheme
  Passepartout.xcodeproj/xcshareddata/xcschemes/PassepartoutIntents.xcscheme
  Passepartout.xcodeproj/xcshareddata/xcschemes/PassepartoutTunnel.xcscheme
  Passepartout/Library/Package.swift
  Passepartout/Library/Sources/CommonLibrary/Domain/BundleConfiguration+AppGroup.swift
  Passepartout/Passepartout.xctestplan
  Passepartout/Tests/LegacyV2CoreDataTests.swift
  Passepartout/Tests/Resources/Profiles.sqlite
  fastlane/Fastfile
Labels: refactoring

#856 Run tests before building
  .github/workflows/release.yml
Labels: bug

#858 Upgrade to Xcode 16
  Passepartout.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Passepartout/Library/Package.swift
  Passepartout/Library/Sources/AppDataProviders/CDProviderRepositoryV3.swift
  Passepartout/Library/Sources/AppUIMain/Views/Profile/NameSection.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileProcessor.swift
  Passepartout/Library/Sources/CommonLibrary/IAP/FallbackReceiptReader.swift
  Passepartout/Library/Sources/CommonLibrary/Mock/MockAppProductHelper.swift
  Passepartout/Library/Sources/CommonUtils/Business/CoreDataRepository.swift
  Passepartout/Library/Sources/CommonUtils/Extensions/UUID+RawRepresentable.swift
  Passepartout/Library/Sources/CommonUtils/IAP/StoreKitHelper.swift
  Passepartout/Library/Sources/UILibrary/L10n/AppError+L10n.swift
  Passepartout/Library/Sources/UILibrary/L10n/PassepartoutKit+L10n.swift
  Passepartout/Library/Sources/UILibrary/Views/Modules/OpenVPNView+Credentials.swift
  Passepartout/Library/Sources/UILibrary/Views/UI/EditableListSection.swift
Labels: bug, refactoring

#859 Import initial remote profiles
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileManager.swift
Labels: bug

#861 Reuse modifier for navigation stacks with close button
  .github/workflows/release.yml
  .github/workflows/test.yml
  Passepartout/Library/Sources/AppUIMain/Views/About/iOS/AboutRouterView+iOS.swift
  Passepartout/Library/Sources/AppUIMain/Views/About/macOS/AboutRouterView+macOS.swift
  Passepartout/Library/Sources/AppUIMain/Views/Profile/macOS/ProfileSplitView+macOS.swift
  Passepartout/Library/Sources/AppUIMain/Views/Provider/VPNProviderServerCoordinator.swift
  Passepartout/Library/Sources/AppUIMain/Views/Provider/iOS/VPNProviderServerView+iOS.swift
  Passepartout/Library/Sources/AppUIMain/Views/Settings/SettingsView.swift
  Passepartout/Library/Sources/UILibrary/Theme/UI/Theme+Modifiers.swift
Labels: refactoring

#862 Strip package dependencies
  Passepartout.xcodeproj/project.pbxproj
  Passepartout.xcodeproj/xcshareddata/xcschemes/Passepartout.xcscheme
  Passepartout.xcodeproj/xcshareddata/xcschemes/PassepartoutIntents.xcscheme
  Passepartout.xcodeproj/xcshareddata/xcschemes/PassepartoutLoginItem.xcscheme
  Passepartout.xcodeproj/xcshareddata/xcschemes/PassepartoutTunnel.xcscheme
  Passepartout/Library/.swiftpm/xcode/xcshareddata/xcschemes/AppUI.xcscheme
  Passepartout/Library/.swiftpm/xcode/xcshareddata/xcschemes/AppUIMain.xcscheme
  Passepartout/Library/.swiftpm/xcode/xcshareddata/xcschemes/AppUITV.xcscheme
  Passepartout/Library/.swiftpm/xcode/xcshareddata/xcschemes/CommonLibrary.xcscheme
  Passepartout/Library/.swiftpm/xcode/xcshareddata/xcschemes/Library-Package.xcscheme
  Passepartout/Library/.swiftpm/xcode/xcshareddata/xcschemes/TunnelLibrary.xcscheme
  Passepartout/Library/.swiftpm/xcode/xcshareddata/xcschemes/UILibrary.xcscheme
  Passepartout/Library/Package.resolved
  Passepartout/Library/Package.swift
  Passepartout/Library/Sources/AppUI/Dummy.swift
Labels: bug, refactoring

#863 Only guard remote fingerprint if local has any
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileManager.swift
Labels: bug

#864 Unify macOS toggles in menu/settings
  Passepartout/Library/Sources/AppUIMain/Views/AppMenu/macOS/AppMenu.swift
  Passepartout/Library/Sources/AppUIMain/Views/Settings/SettingsSectionGroup.swift
  Passepartout/Library/Sources/UILibrary/L10n/SwiftGen+Strings.swift
  Passepartout/Library/Sources/UILibrary/Resources/en.lproj/Localizable.strings
Labels: enhancement, macOS

#865 Decouple Mac settings from AppMenu
  Passepartout/App/AppDelegate.swift
  Passepartout/App/PassepartoutApp.swift
  Passepartout/App/Platforms/App+macOS.swift
  Passepartout/Library/Sources/AppUIMain/Business/MacSettingsModel.swift
  Passepartout/Library/Sources/AppUIMain/Views/AppMenu/macOS/AppMenu+Model.swift
  Passepartout/Library/Sources/AppUIMain/Views/AppMenu/macOS/AppMenu.swift
  Passepartout/Library/Sources/AppUIMain/Views/Settings/SettingsSectionGroup.swift
Labels: bug, refactoring

#867 Import migrated profiles
  Passepartout/Library/Sources/AppUIMain/Views/App/AppCoordinator.swift
  Passepartout/Library/Sources/AppUIMain/Views/Migration/MigrateView+Content.swift
  Passepartout/Library/Sources/AppUIMain/Views/Migration/MigrateView+Model.swift
  Passepartout/Library/Sources/AppUIMain/Views/Migration/MigrateView+Section.swift
  Passepartout/Library/Sources/AppUIMain/Views/Migration/MigrateView+Table.swift
  Passepartout/Library/Sources/AppUIMain/Views/Migration/MigrateView.swift
  Passepartout/Library/Sources/CommonLibrary/Business/MigrationManager.swift
  Passepartout/Library/Sources/CommonLibrary/Domain/MigratableProfile.swift
  Passepartout/Library/Sources/CommonLibrary/Domain/MigrationStatus.swift
  Passepartout/Shared/AppContext+Shared.swift
Labels: enhancement, refactoring

#871 Copy release receipt to tunnel
  Passepartout.xcodeproj/project.pbxproj
  Passepartout/Library/Sources/CommonUtils/Extensions/Bundle+Extensions.swift
  Passepartout/Library/Sources/UILibrary/Business/AppContext.swift
  Passepartout/Shared/Shared+App.swift
Labels: bug

#873 Add explicit environment objects to TableColumn
  Passepartout/Library/Sources/AppUIMain/Views/Migration/MigrateView+Section.swift
  Passepartout/Library/Sources/AppUIMain/Views/Migration/MigrateView+Table.swift
  Passepartout/Library/Sources/AppUIMain/Views/Provider/macOS/VPNProviderServerView+macOS.swift
  Passepartout/LoginItem/AppDelegate.swift
Labels: regression, macOS

#875 Modernize check for TestFlight build
  Passepartout/Library/Sources/CommonLibrary/IAP/IAPManager.swift
  Passepartout/Library/Sources/CommonUtils/Business/SandboxChecker.swift
Labels: refactoring

#876 Nested ZStack modifiers in progress/empty modifiers
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileContainerView.swift
  Passepartout/Library/Sources/AppUIMain/Views/Migration/MigrateView.swift
  Passepartout/Library/Sources/UILibrary/Extensions/View+Environment.swift
  Passepartout/Library/Sources/UILibrary/Theme/UI/Theme+Modifiers.swift
Labels: bug, refactoring

#877 Refactor modal size to be a modifer parameter
  Passepartout/Library/Sources/AppUIMain/Views/App/AppCoordinator.swift
  Passepartout/Library/Sources/AppUIMain/Views/Provider/iOS/VPNProviderServerView+iOS.swift
  Passepartout/Library/Sources/UILibrary/Theme/Platforms/Theme+iOS.swift
  Passepartout/Library/Sources/UILibrary/Theme/Platforms/Theme+macOS.swift
  Passepartout/Library/Sources/UILibrary/Theme/Theme.swift
  Passepartout/Library/Sources/UILibrary/Theme/UI/Theme+Modifiers.swift
Labels: refactoring

#880 Revert "Modernize check for TestFlight build"
  Passepartout/Library/Sources/CommonUtils/Business/SandboxChecker.swift
Labels: bug

#881 Improve migrate header on iOS
  Passepartout/Library/Sources/AppUIMain/Views/Migration/MigrateContentView+List.swift
  Passepartout/Library/Sources/AppUIMain/Views/Migration/MigrateContentView+Table.swift
  Passepartout/Shared/AppContext+Shared.swift
Labels: enhancement, refactoring

#882 Perform migrate + import in one step
  Passepartout.xcodeproj/xcshareddata/xcschemes/Passepartout.xcscheme
  Passepartout/Library/Sources/AppUIMain/Views/Migration/MigrateButton.swift
  Passepartout/Library/Sources/AppUIMain/Views/Migration/MigrateContentView+List.swift
  Passepartout/Library/Sources/AppUIMain/Views/Migration/MigrateContentView+Table.swift
  Passepartout/Library/Sources/AppUIMain/Views/Migration/MigrateContentView.swift
  Passepartout/Library/Sources/AppUIMain/Views/Migration/MigrateView+Model.swift
  Passepartout/Library/Sources/AppUIMain/Views/Migration/MigrateView.swift
  Passepartout/Library/Sources/AppUIMain/Views/Migration/MigrateViewStep.swift
  Passepartout/Library/Sources/CommonLibrary/Business/MigrationManager.swift
  Passepartout/Library/Sources/CommonLibrary/Domain/MigrationStatus.swift
  Passepartout/Library/Sources/UILibrary/L10n/SwiftGen+Strings.swift
  Passepartout/Library/Sources/UILibrary/Resources/en.lproj/Localizable.strings
  Passepartout/Shared/AppContext+Shared.swift
  Passepartout/Shared/Shared.swift
Labels: enhancement, refactoring

#883 Resolve excessive profile reloads
  Passepartout.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Passepartout/Library/Package.swift
  Passepartout/Library/Sources/AppDataProviders/Strategy/CDProviderRepositoryV3.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileManager.swift
  Passepartout/Library/Sources/CommonLibrary/IAP/IAPManager.swift
  Passepartout/Library/Sources/CommonUtils/Business/CoreDataRepository.swift
  Passepartout/Library/Sources/UILibrary/Business/AppContext.swift
  Passepartout/Library/Sources/UILibrary/Mock/AppContext+Mock.swift
  Passepartout/Shared/AppContext+Shared.swift
Labels: bug, enhancement, refactoring

#884 Discard old profiles once migrated
  Passepartout/Library/Sources/AppUIMain/Views/Migration/MigrateView.swift
Labels: bug

#886 Do not discard migrated profiles in TestFlight
  Passepartout/Library/Sources/AppUIMain/Views/Migration/MigrateView.swift
Labels: enhancement

#888 Clear previous remote import task
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileManager.swift
Labels: bug

#891 Show upgrade icon in profiles list
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileRowView.swift
  Passepartout/Library/Sources/AppUIMain/Views/Profile/ProfileCoordinator.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileManager.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileProcessor.swift
  Passepartout/Library/Sources/CommonLibrary/IAP/AppFeatureRequiring.swift
  Passepartout/Library/Sources/CommonLibrary/IAP/IAPManager+Verify.swift
  Passepartout/Library/Sources/UILibrary/Mock/AppContext+Mock.swift
  Passepartout/Shared/Shared+App.swift
  Passepartout/Tunnel/PacketTunnelProvider.swift
Labels: enhancement, refactoring

#892 Reload receipt on purchase
  Passepartout/Library/Sources/AppUIMain/Views/App/InstalledProfileView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileContainerView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileGridView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileListView.swift
  Passepartout/Library/Sources/UILibrary/Views/Paywall/PaywallView.swift
Labels: bug

#893 Verify profile before presenting interactive login
  Passepartout/Library/Sources/UILibrary/Views/UI/TunnelToggleButton.swift
Labels: bug

#895 Update profiles requirements on new in-app receipt
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileManager.swift
  Passepartout/Library/Sources/UILibrary/Business/AppContext.swift
Labels: bug

#896 Check provider requirements before connecting
  Passepartout.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Passepartout/Library/Package.swift
  Passepartout/Library/Sources/UILibrary/L10n/AppError+L10n.swift
  Passepartout/Library/Sources/UILibrary/Views/UI/TunnelToggleButton.swift
Labels: bug

#901 Test ProfileManager
  Passepartout/Library/Sources/CommonLibrary/Business/ExtendedTunnel.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileManager.swift
  Passepartout/Library/Sources/CommonLibrary/Strategy/InAppProcessor.swift
  Passepartout/Library/Sources/CommonLibrary/Strategy/InMemoryProfileRepository.swift
  Passepartout/Library/Sources/CommonLibrary/Strategy/ProfileProcessor.swift
  Passepartout/Library/Sources/CommonLibrary/Strategy/TunnelProcessor.swift
  Passepartout/Library/Sources/UILibrary/Mock/AppContext+Mock.swift
  Passepartout/Library/Tests/CommonLibraryTests/Mock/MockProfileProcessor.swift
  Passepartout/Library/Tests/CommonLibraryTests/ProfileManagerTests.swift
  Passepartout/Shared/Shared+App.swift
Labels: bug, refactoring

#904 Test MigrationManager
  Passepartout/Library/Sources/CommonLibrary/Business/MigrationManager.swift
  Passepartout/Library/Sources/CommonLibrary/Extensions/ProfileManager+Importer.swift
  Passepartout/Library/Tests/CommonLibraryTests/MigrationManagerTests.swift
  Passepartout/Library/Tests/CommonLibraryTests/Mock/MockMigrationManagerImporter.swift
  Passepartout/Library/Tests/CommonLibraryTests/Mock/MockProfileMigrationStrategy.swift
Labels: refactoring

#905 Fetch products from scratch each time
  Passepartout/Library/Sources/CommonUtils/IAP/StoreKitHelper.swift
Labels: bug

#906 Fix shared profile not updated on provider server selection
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileRowView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProviderEntitySelector.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileManager.swift
  Passepartout/Library/Sources/CommonLibrary/Extensions/ProfileManager+Importer.swift
  Passepartout/Library/Sources/UILibrary/Business/ProfileEditor.swift
  Passepartout/Library/Tests/CommonLibraryTests/ProfileManagerTests.swift
Labels: bug

#907 Do not disconnect active profile on remote import
  Passepartout.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Passepartout/Library/Package.swift
Labels: bug

#908 Polish TV profile view
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileRowView.swift
  Passepartout/Library/Sources/AppUITV/Views/App/AppCoordinator.swift
  Passepartout/Library/Sources/AppUITV/Views/Profile/ActiveProfileView.swift
  Passepartout/Library/Sources/AppUITV/Views/Profile/ProfileListView.swift
  Passepartout/Library/Sources/AppUITV/Views/Profile/ProfileView.swift
  Passepartout/Library/Sources/AppUITV/Views/Settings/SettingsView.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileManager.swift
  Passepartout/Library/Sources/UILibrary/L10n/SwiftGen+Strings.swift
  Passepartout/Library/Sources/UILibrary/Resources/en.lproj/Localizable.strings
  Passepartout/Library/Sources/UILibrary/Theme/Theme+Extensions.swift
Labels: enhancement, tvOS

#910 Minor UI fixes
  Passepartout.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Passepartout/Library/Package.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/AppCoordinator.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/InstalledProfileView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileContextMenu.swift
  Passepartout/Library/Sources/AppUIMain/Views/Diagnostics/ReportIssueButton.swift
  Passepartout/Library/Sources/AppUITV/Views/Profile/ActiveProfileView.swift
  Passepartout/Library/Sources/AppUITV/Views/Profile/ProfileListView.swift
  Passepartout/Library/Sources/AppUITV/Views/Profile/ProfileView.swift
  Passepartout/Library/Sources/UILibrary/Views/UI/TunnelToggleButton.swift
Labels: refactoring, tvOS

#911 List other modules in TV active profile
  Passepartout/Library/Sources/AppUITV/Views/Profile/ActiveProfileView.swift
Labels: bug, tvOS

#916 Fix layout of multiline modules
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileCardView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileRowView.swift
Labels: bug

#918 Share migrated TV profiles
  Passepartout/App/App.entitlements
  Passepartout/App/App.plist
  Passepartout/Config.xcconfig
  Passepartout/Library/Sources/CommonLibrary/Business/MigrationManager.swift
  Passepartout/Library/Sources/CommonLibrary/Domain/BundleConfiguration+Main.swift
  Passepartout/Library/Sources/CommonLibrary/Domain/Constants.swift
  Passepartout/Library/Sources/CommonLibrary/Extensions/ProfileManager+Importer.swift
  Passepartout/Library/Sources/CommonLibrary/Resources/Constants.json
  Passepartout/Library/Sources/LegacyV2/Domain/MapperV2.swift
  Passepartout/Library/Sources/LegacyV2/Strategy/ProfileV2MigrationStrategy.swift
  Passepartout/Library/Tests/CommonLibraryTests/Mock/MockMigrationManagerImporter.swift
  Passepartout/Shared/AppContext+Shared.swift
  Passepartout/Tests/MigrationManagerTests.swift
Labels: bug

#923 Simplify paywall entities
  Passepartout.xcodeproj/xcshareddata/xcschemes/Passepartout.xcscheme
  Passepartout/Library/Sources/AppUIMain/Views/App/AppCoordinator.swift
  Passepartout/Library/Sources/AppUIMain/Views/Profile/ProfileCoordinator.swift
  Passepartout/Library/Sources/AppUIMain/Views/Profile/StorageSection.swift
  Passepartout/Library/Sources/AppUITV/Views/App/AppCoordinator.swift
  Passepartout/Library/Sources/UILibrary/L10n/SwiftGen+Strings.swift
  Passepartout/Library/Sources/UILibrary/Resources/en.lproj/Localizable.strings
  Passepartout/Library/Sources/UILibrary/Theme/UI/Theme+Modifiers.swift
  Passepartout/Library/Sources/UILibrary/Views/UI/PaywallModifier+Reason.swift
  Passepartout/Library/Sources/UILibrary/Views/UI/PaywallModifier.swift
  Passepartout/Library/Sources/UILibrary/Views/UI/PurchaseAlertModifier.swift
  Passepartout/Library/Sources/UILibrary/Views/UI/PurchaseButtonModifier.swift
  Passepartout/Library/Sources/UILibrary/Views/UI/PurchaseRequiredButton.swift
Labels: bug, refactoring

#925 Fix missing beta check on tvOS
  Passepartout/Library/Sources/CommonLibrary/Business/IAPManager.swift
  Passepartout/Library/Sources/CommonUtils/Business/TestFlightChecker.swift
Labels: bug, tvOS

#926 Add some preliminary templates for manual tests
  .github/ISSUE_TEMPLATE/001-issue.md
  .github/ISSUE_TEMPLATE/002-copyright_clause.md
  .github/ISSUE_TEMPLATE/010-test_in_app.md
  .github/ISSUE_TEMPLATE/011-test_migration.md
  .github/ISSUE_TEMPLATE/012-test_release.md
  .github/ISSUE_TEMPLATE/020-test_platforms.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation

#927 Improve provider servers responsiveness on iOS
  Passepartout/Library/Sources/AppUIMain/Views/Providers/iOS/VPNProviderServerView+iOS.swift
Labels: bug, iOS

#934 Localize WireGuard errors
  Passepartout.xcodeproj/project.pbxproj
  Passepartout.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Passepartout/Library/Package.swift
  Passepartout/Library/Sources/UILibrary/L10n/SwiftGen+Strings.swift
  Passepartout/Library/Sources/UILibrary/Resources/en.lproj/Localizable.strings
  Passepartout/Tests/LocalizationTests.swift
  swiftgen.yml
Labels: bug

#935 Add view in "About" about purchased products
  Passepartout/Library/Sources/AppUIMain/Views/About/AboutCoordinator.swift
  Passepartout/Library/Sources/AppUIMain/Views/About/AboutCoordinatorRoute.swift
  Passepartout/Library/Sources/AppUIMain/Views/About/iOS/AboutContentView+iOS.swift
  Passepartout/Library/Sources/AppUIMain/Views/About/macOS/AboutContentView+macOS.swift
  Passepartout/Library/Sources/AppUITV/Views/App/AppCoordinator.swift
  Passepartout/Library/Sources/AppUITV/Views/App/AppCoordinatorRoute.swift
  Passepartout/Library/Sources/AppUITV/Views/Settings/SettingsView.swift
  Passepartout/Library/Sources/CommonLibrary/Business/IAPManager.swift
  Passepartout/Library/Sources/CommonLibrary/Strategy/InAppProcessor.swift
  Passepartout/Library/Sources/UILibrary/L10n/SwiftGen+Strings.swift
  Passepartout/Library/Sources/UILibrary/Mock/AppContext+Mock.swift
  Passepartout/Library/Sources/UILibrary/Resources/en.lproj/Localizable.strings
  Passepartout/Library/Sources/UILibrary/Views/About/PurchasedView.swift
  Passepartout/Shared/Shared+App.swift
Labels: enhancement

#938 Add "Refresh infrastructure" in server lists
  Passepartout/Library/Sources/AppUIMain/Views/Providers/ProviderContentModifier.swift
  Passepartout/Library/Sources/AppUIMain/Views/Providers/ProviderEntitySelector.swift
  Passepartout/Library/Sources/AppUIMain/Views/VPN/VPNFiltersView+Model.swift
  Passepartout/Library/Sources/AppUIMain/Views/VPN/VPNFiltersView.swift
  Passepartout/Library/Sources/AppUIMain/Views/VPN/VPNProviderContentModifier.swift
  Passepartout/Library/Sources/AppUIMain/Views/VPN/VPNProviderServerCoordinator.swift
  Passepartout/Library/Sources/AppUIMain/Views/VPN/VPNProviderServerView+Container.swift
  Passepartout/Library/Sources/AppUIMain/Views/VPN/VPNProviderServerView.swift
  Passepartout/Library/Sources/AppUIMain/Views/VPN/iOS/VPNProviderServerContentView+iOS.swift
  Passepartout/Library/Sources/AppUIMain/Views/VPN/iOS/VPNProviderServerView+iOS.swift
  Passepartout/Library/Sources/AppUIMain/Views/VPN/macOS/VPNProviderServerContentView+macOS.swift
  Passepartout/Library/Sources/AppUIMain/Views/VPN/macOS/VPNProviderServerView+macOS.swift
  Passepartout/Library/Sources/CommonUtils/Views/View+Extensions.swift
  Passepartout/Library/Sources/UILibrary/L10n/SwiftGen+Strings.swift
  Passepartout/Library/Sources/UILibrary/Resources/en.lproj/Localizable.strings
  Passepartout/Library/Sources/UILibrary/Views/UI/RefreshInfrastructureButton.swift
Labels: enhancement

#939 Simplify VPNProviderServerView components
  Passepartout/Library/Sources/AppUIMain/Views/VPN/VPNProviderServerView+Container.swift
  Passepartout/Library/Sources/AppUIMain/Views/VPN/VPNProviderServerView.swift
  Passepartout/Library/Sources/AppUIMain/Views/VPN/iOS/VPNProviderServer+Container+iOS.swift
  Passepartout/Library/Sources/AppUIMain/Views/VPN/iOS/VPNProviderServer+Content+iOS.swift
  Passepartout/Library/Sources/AppUIMain/Views/VPN/macOS/VPNProviderServer+Container+macOS.swift
  Passepartout/Library/Sources/AppUIMain/Views/VPN/macOS/VPNProviderServer+Content+macOS.swift
Labels: refactoring

#941 Connect on provider server selection
  Passepartout.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Passepartout/Library/Package.swift
  Passepartout/Library/Sources/AppUIMain/Views/Providers/ProviderEntitySelector.swift
  Passepartout/Library/Sources/AppUIMain/Views/VPN/VPNProviderServerCoordinator.swift
  Passepartout/Library/Sources/CommonLibrary/Strategy/NEProfileRepository.swift
Labels: enhancement

#942 Retain on-demand flag on save profile
  Passepartout.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Passepartout/Library/Package.swift
Labels: regression

#943 Improve TV settings screen
  Passepartout/Library/Sources/AppUITV/Views/App/AppCoordinator.swift
  Passepartout/Library/Sources/AppUITV/Views/App/AppCoordinatorRoute.swift
  Passepartout/Library/Sources/AppUITV/Views/Settings/DonateViewModifier.swift
  Passepartout/Library/Sources/AppUITV/Views/Settings/SettingsView.swift
  Passepartout/Library/Sources/CommonUtils/Views/GenericCreditsView.swift
  Passepartout/Library/Sources/CommonUtils/Views/View+Extensions.swift
  Passepartout/Library/Sources/UILibrary/Views/About/PurchasedView.swift
  Passepartout/Library/Sources/UILibrary/Views/Paywall/PaywallView.swift
Labels: bug, tvOS

#944 Fix regressions in L&F
  Passepartout/Library/Sources/CommonUtils/Views/View+Extensions.swift
  Passepartout/Library/Sources/UILibrary/Views/About/PurchasedView.swift
Labels: bug

#945 Do not present server selector if ineligible
  Passepartout/Library/Sources/UILibrary/Views/UI/TunnelToggleButton.swift
Labels: bug

#946 Add provider profile from toolbar
  Passepartout.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Passepartout/Library/Package.swift
  Passepartout/Library/Sources/AppUIMain/Business/ProfileImporter.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/AddProfileMenu.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/AppCoordinator.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/AppToolbar.swift
  Passepartout/Library/Sources/AppUIMain/Views/Profile/ProfileCoordinator.swift
  Passepartout/Library/Sources/AppUIMain/Views/Profile/iOS/ProfileEditView+iOS.swift
  Passepartout/Library/Sources/AppUIMain/Views/Profile/macOS/ProfileSplitView+macOS.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileManager.swift
  Passepartout/Library/Sources/CommonLibrary/Domain/EditableProfile.swift
  Passepartout/Library/Sources/CommonLibrary/Domain/ModuleType+New.swift
  Passepartout/Library/Sources/UILibrary/Business/ProfileEditor.swift
  Passepartout/Library/Sources/UILibrary/L10n/SwiftGen+Strings.swift
  Passepartout/Library/Sources/UILibrary/Resources/en.lproj/Localizable.strings
  Passepartout/Library/Sources/UILibrary/Theme/Theme+ImageName.swift
  Passepartout/Library/Tests/CommonLibraryTests/ProfileManagerTests.swift
Labels: enhancement

#947 Different styles for profile menu based on context
  Passepartout/Library/Package.resolved
  Passepartout/Library/Sources/AppUIMain/Views/App/InstalledProfileView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileContextMenu.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileGridView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileListView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileRowView.swift
  Passepartout/Library/Sources/AppUIMain/Views/Modules/OpenVPNView.swift
  Passepartout/Library/Sources/UILibrary/L10n/SwiftGen+Strings.swift
  Passepartout/Library/Sources/UILibrary/Resources/en.lproj/Localizable.strings
Labels: bug, refactoring

#953 Improve layout of installed profile
  Passepartout/Library/Sources/AppUIMain/Views/App/InstalledProfileView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileCardView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileContainerView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileDuplicateButton.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileImporterModifier.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/TunnelRestartButton.swift
  Passepartout/Library/Sources/AppUITV/Views/Profile/ActiveProfileView.swift
  Passepartout/Library/Sources/AppUITV/Views/Profile/ProfileView.swift
  Passepartout/Library/Sources/AppUITV/Views/UI/ListRowView.swift
  Passepartout/Library/Sources/UILibrary/L10n/SwiftGen+Strings.swift
  Passepartout/Library/Sources/UILibrary/Resources/en.lproj/Localizable.strings
  Passepartout/Library/Sources/UILibrary/Theme/Platforms/Theme+tvOS.swift
  Passepartout/Library/Sources/UILibrary/Theme/Theme.swift
  Passepartout/Library/Sources/UILibrary/Views/Paywall/PaywallView.swift
  Passepartout/Library/Sources/UILibrary/Views/UI/TunnelToggleButton.swift
Labels: enhancement, refactoring

#957 Improve bump script with positional arguments
  ci/bump-no-log.sh
  ci/bump-since.sh
  ci/bump-version.sh
  ci/bump.sh
  ci/update-bundled-api.sh
  fastlane/Fastfile
Labels: enhancement

#961 Separate AppContext for previews and UI testing
  Passepartout.xcodeproj/project.pbxproj
  Passepartout/App/AppDelegate.swift
  Passepartout/Library/.swiftpm/xcode/xcshareddata/xcschemes/Library-Package.xcscheme
  Passepartout/Library/Sources/AppUIMain/Views/About/AboutCoordinator.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/AppCoordinator.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/AppToolbar.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/InstalledProfileView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/OnboardingModifier.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileCardView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileContainerView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileContextMenu.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileGridView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileListView.swift
  Passepartout/Library/Sources/AppUIMain/Views/App/ProfileRowView.swift
  Passepartout/Library/Sources/AppUIMain/Views/Diagnostics/DiagnosticsView.swift
  Passepartout/Library/Sources/AppUIMain/Views/Profile/ModuleDetailView.swift
  Passepartout/Library/Sources/AppUIMain/Views/Profile/ProfileCoordinator.swift
  Passepartout/Library/Sources/AppUIMain/Views/Profile/macOS/ModuleListView+macOS.swift
  Passepartout/Library/Sources/AppUITV/Views/App/AppCoordinator.swift
  Passepartout/Library/Sources/AppUITV/Views/Profile/ActiveProfileView.swift
  Passepartout/Library/Sources/AppUITV/Views/Profile/ProfileListView.swift
  Passepartout/Library/Sources/AppUITV/Views/Profile/ProfileView.swift
  Passepartout/Library/Sources/AppUITV/Views/Settings/SettingsView.swift
  Passepartout/Library/Sources/CommonLibrary/Business/ProfileManager.swift
  Passepartout/Library/Sources/CommonLibrary/Strategy/InAppProcessor.swift
  Passepartout/Library/Sources/CommonLibrary/Strategy/ProfileProcessor.swift
  Passepartout/Library/Sources/UILibrary/Extensions/View+Environment.swift
  Passepartout/Library/Sources/UILibrary/Previews/AppContext+Previews.swift
  Passepartout/Library/Sources/UILibrary/Previews/Profile+Previews.swift
  Passepartout/Library/Sources/UILibrary/Views/UI/ConnectionStatusText.swift
  Passepartout/Library/Tests/CommonLibraryTests/Mock/MockProfileProcessor.swift
  Passepartout/Library/Tests/CommonLibraryTests/ProfileManagerTests.swift
  Passepartout/Shared/AppContext+Shared.swift
  Passepartout/Shared/Shared+App.swift
  Passepartout/Shared/Shared.swift
  Passepartout/Shared/Testing/AppContext+Testing.swift
  Passepartout/Shared/Testing/ProfileManager+Testing.swift
Labels: bug, refactoring, testing

#964 Extend ProfileManager events
  Library/Sources/CommonLibrary/Business/ProfileManager.swift
  Library/Tests/AppUIMainTests/ProfileImporterTests.swift
  Library/Tests/CommonLibraryTests/ExtendedTunnelTests.swift
  Library/Tests/CommonLibraryTests/IAPManagerTests.swift
  Library/Tests/CommonLibraryTests/ProfileManagerTests.swift
  Library/Tests/UILibraryTests/ProfileEditorTests.swift
Labels: bug, testing

#963 Transparent logo in version screen
  Library/Sources/AppUIMain/Views/About/macOS/AboutContentView+macOS.swift
  Library/Sources/AppUITV/Views/Profile/ProfileView.swift
  Library/Sources/AppUITV/Views/Settings/SettingsView.swift
  Library/Sources/UILibrary/Theme/Platforms/Theme+tvOS.swift
  Library/Sources/UILibrary/Views/About/VersionView.swift
  Passepartout/App/Assets.xcassets/Logo.imageset/Logo@2x.png
  Passepartout/App/Assets.xcassets/Logo.imageset/Logo@3x.png
Labels: enhancement, macOS, tvOS

#965 Update release notes on bump
  ci/bump.sh
  ci/update-bundled-api.sh
  ci/update-release-notes.sh
  fastlane/Fastfile
  fastlane/metadata/iOS/de-DE/release_notes.txt
  fastlane/metadata/iOS/el/release_notes.txt
  fastlane/metadata/iOS/en-US/release_notes.txt
  fastlane/metadata/iOS/es-MX/release_notes.txt
  fastlane/metadata/iOS/fr-FR/release_notes.txt
  fastlane/metadata/iOS/it/release_notes.txt
  fastlane/metadata/iOS/nl-NL/release_notes.txt
  fastlane/metadata/iOS/pl/release_notes.txt
  fastlane/metadata/iOS/pt-BR/release_notes.txt
  fastlane/metadata/iOS/ru/release_notes.txt
  fastlane/metadata/iOS/sv/release_notes.txt
  fastlane/metadata/macOS/en-US/release_notes.txt
  fastlane/metadata/symlink-base.sh
  fastlane/metadata/symlink-l10n.sh
  fastlane/metadata/symlink-release-notes.sh
  fastlane/metadata/tvOS/en-US/release_notes.txt
Labels: enhancement

#966 Add guidance for OpenVPN provider credentials
  Library/Package.resolved
  Library/Package.swift
  Library/Sources/AppDataProviders/Domain/CDProviderV3.swift
  Library/Sources/AppDataProviders/Domain/CoreDataMapper.swift
  Library/Sources/AppDataProviders/Domain/DomainMapper.swift
  Library/Sources/AppDataProviders/Providers.xcdatamodeld/Providers.xcdatamodel/contents
  Library/Sources/AppDataProviders/Strategy/CDProviderRepositoryV3.swift
  Library/Sources/AppUIMain/Views/Modules/OpenVPNView.swift
  Library/Sources/CommonAPI/API/v5/providers/index.json
  Library/Sources/CommonLibrary/Domain/ProfileAttributes.swift
  Library/Sources/UILibrary/L10n/SwiftGen+Strings.swift
  Library/Sources/UILibrary/Resources/en.lproj/Localizable.strings
  Library/Sources/UILibrary/Views/Modules/Extensions/OpenVPNModule+Extensions.swift
  Library/Sources/UILibrary/Views/Modules/OpenVPNView+Credentials.swift
  Passepartout.xcodeproj/xcshareddata/xcschemes/Passepartout.xcscheme
Labels: enhancement
