Repository passepartoutvpn/passepartout, pull requests merged in 2024-01, with the labels that each got.

#445 fix: added missing uk translation
  Passepartout/App/uk.lproj/Localizable.strings
  scripts/util/export-for-translations.sh
  scripts/util/import-onesky-translations.sh
  scripts/util/list-untranslated.sh
Labels: bug

#447 Restore proper OpenVPN connectivity
  CHANGELOG.md
  Gemfile.lock
  Passepartout.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Passepartout/App/Info.plist
  Passepartout/App/L10n/OpenVPN+L10n.swift
  Passepartout/Launcher/Info.plist
  Passepartout/Mac/Info.plist
  Passepartout/Tunnel/Info.plist
  PassepartoutLibrary/Package.swift
Labels: regression

#449 Upload tvOS build to TestFlight
  .env.ios
  .env.mac
  .env.tvos
  .github/workflows/release.yml
Labels: enhancement

#452 Revisit submission of OpenVPN diagnostic report
  Passepartout.xcodeproj/xcshareddata/xcschemes/Passepartout.xcscheme
  Passepartout/App/Extensions/DebugLog+Constants.swift
  Passepartout/App/L10n/Unlocalized.swift
  Passepartout/App/Views/DebugLogView.swift
  Passepartout/App/Views/DiagnosticsView+OpenVPN.swift
  Passepartout/App/Views/DiagnosticsView.swift
  Passepartout/App/Views/ReportIssueView.swift
  PassepartoutLibrary/Sources/PassepartoutFrontend/Managers/ProductManager.swift
  PassepartoutLibrary/Sources/PassepartoutVPN/Extensions/DebugLog+Extensions.swift
Labels: enhancement

#453 Add tvOS build to beta/review CI jobs
  .github/workflows/release.yml
  Passepartout/App/Info.plist
  Passepartout/Launcher/Info.plist
  Passepartout/Mac/Info.plist
  Passepartout/Tunnel/Info.plist
Labels: enhancement

#460 Regression in purchase elegibility predicate
  CHANGELOG.md
  PassepartoutLibrary/Sources/PassepartoutFrontend/Managers/ProductManager.swift
Labels: regression

#462 Rewrite wrong refund logic
  CHANGELOG.md
  Gemfile.lock
  Passepartout/App/Constants/Constants+App.swift
  Passepartout/App/Context/AppContext.swift
  PassepartoutLibrary/Sources/PassepartoutFrontend/Managers/ProductManager.swift
Labels: bug

#463 On-demand not applying to wired connections
  CHANGELOG.md
  PassepartoutLibrary/Sources/PassepartoutVPNImpl/Extensions/OnDemand+Rules.swift
Labels: regression, macOS

#465 Rework how purchasable products are presented
  CHANGELOG.md
  Passepartout/App/Views/PaywallView+Purchase.swift
  PassepartoutLibrary/Sources/PassepartoutFrontend/Managers/ProductManager.swift
  PassepartoutLibrary/Tests/PassepartoutFrontendTests/ProductManagerTests.swift
Labels: bug

#467 Split Apple TV purchase
  Passepartout/App/Views/AddProviderView.swift
  Passepartout/App/Views/PaywallView+Purchase.swift
  Passepartout/App/Views/PaywallView.swift
  PassepartoutLibrary/Sources/PassepartoutFrontend/Managers/ProductManager.swift
  PassepartoutLibrary/Tests/PassepartoutFrontendTests/ProductManagerTests.swift
Labels: bug

#471 Unintended sensitive data in issue reports
  Passepartout/App/Views/EndpointView+OpenVPN.swift
  Passepartout/App/Views/EndpointView+WireGuard.swift
  PassepartoutLibrary/Sources/PassepartoutVPNImpl/Strategies/KeychainSecretRepository.swift
Labels: regression

#472 Drop deprecated .disconnectsIfNotMatching
  PassepartoutLibrary/Sources/PassepartoutVPN/Domain/Profile+OnDemand.swift
  PassepartoutLibrary/Sources/PassepartoutVPNImpl/Strategies/CDProfileRepository.swift
Labels: refactoring

#481 Update restricted profile except expiration
  CHANGELOG.md
  Passepartout/App/Context/AppContext.swift
Labels: bug

#484 Improve some in-app tests
  PassepartoutLibrary/Sources/PassepartoutFrontend/Domain/AppType.swift
  PassepartoutLibrary/Sources/PassepartoutFrontend/Managers/ProductManager.swift
  PassepartoutLibrary/Tests/PassepartoutFrontendTests/ProductManagerTests.swift
Labels: refactoring

#486 Override profile list selection color
  CHANGELOG.md
  Passepartout/App/Constants/Theme.swift
  Passepartout/App/Views/OrganizerView+Profiles.swift
  Passepartout/App/Views/VPNToggle.swift
Labels: bug, iOS
