Repository passepartoutvpn/passepartout, pull requests merged in 2025-01, with the labels that each got.

#1048 Skip backup repository on simulator
  Library/Sources/CommonUtils/Business/CoreDataRepository.swift
  Passepartout/App/Context/AppContext+Shared.swift
Labels: bug

#1049 Set up local profiles observer once
  Library/Sources/UILibrary/Business/AppContext.swift
Labels: bug

#1050 Fix on-demand SSID not being added on macOS
  Library/Sources/CommonUtils/Business/CoreLocationWifiObserver.swift
Labels: regression, macOS

#1051 Sync local profiles consistently
  Library/Package.resolved
  Library/Package.swift
  Library/Sources/CommonLibrary/Strategy/NEProfileRepository.swift
Labels: bug

#1052 Edit OpenVPN remotes
  Library/Sources/AppUIMain/Views/Modules/OpenVPNView+Configuration.swift
  Library/Sources/AppUIMain/Views/Modules/OpenVPNView+Remotes.swift
  Library/Sources/AppUIMain/Views/Modules/OpenVPNView.swift
  Library/Sources/UILibrary/L10n/Strings+Unlocalized.swift
  Library/Sources/UILibrary/L10n/SwiftGen+Strings.swift
  Library/Sources/UILibrary/Resources/de.lproj/Localizable.strings
  Library/Sources/UILibrary/Resources/el.lproj/Localizable.strings
  Library/Sources/UILibrary/Resources/en.lproj/Localizable.strings
  Library/Sources/UILibrary/Resources/es.lproj/Localizable.strings
  Library/Sources/UILibrary/Resources/fr.lproj/Localizable.strings
  Library/Sources/UILibrary/Resources/it.lproj/Localizable.strings
  Library/Sources/UILibrary/Resources/nl.lproj/Localizable.strings
  Library/Sources/UILibrary/Resources/pl.lproj/Localizable.strings
  Library/Sources/UILibrary/Resources/pt.lproj/Localizable.strings
  Library/Sources/UILibrary/Resources/ru.lproj/Localizable.strings
  Library/Sources/UILibrary/Resources/sv.lproj/Localizable.strings
  Library/Sources/UILibrary/Resources/uk.lproj/Localizable.strings
  Library/Sources/UILibrary/Resources/zh-Hans.lproj/Localizable.strings
  Library/Sources/UILibrary/Views/UI/EndpointCardView.swift
Labels: enhancement

#1053 Restore server entitlement for WireGuard to work on macOS
  Passepartout/Tunnel/Tunnel.entitlements
Labels: regression, macOS

#1054 Provide default values for non-frozen enums
  Library/Sources/AppDataProviders/Domain/VPNServerParameters+CoreData.swift
  Library/Sources/AppUIMain/Views/Modules/DNSView.swift
  Library/Sources/AppUIMain/Views/Modules/OnDemandView.swift
  Library/Sources/UILibrary/L10n/Modules/DNSModule+L10n.swift
  Library/Sources/UILibrary/L10n/Modules/OpenVPNModule+L10n.swift
  Library/Sources/UILibrary/L10n/PassepartoutKit+L10n.swift
  README.md
Labels: refactoring

#1056 Add EULA and privacy policy in paywall
  Packages/App/Sources/CommonLibrary/Domain/Constants.swift
  Packages/App/Sources/CommonLibrary/Resources/Constants.json
  Packages/App/Sources/UILibrary/L10n/Strings+Unlocalized.swift
  Packages/App/Sources/UILibrary/Views/Paywall/PaywallView.swift
Labels: enhancement

#1064 Retain WireGuardAdapterDelegate
  Packages/PassepartoutKit-Framework/Package.swift
  Packages/PassepartoutWireGuardGo/Sources/PassepartoutWireGuardGo/WireGuardConnection.swift
Labels: regression

#1074 Assume .appleTV to be enough on tvOS
  Packages/App/Sources/CommonLibrary/IAP/IAPManager+Verify.swift
Labels: regression

#1078 Fix error alert when importing files from external apps
  Packages/App/Sources/AppUIMain/Business/ProfileImporter.swift
  Packages/App/Sources/UILibrary/L10n/AppError+L10n.swift
  Packages/App/Sources/UILibrary/L10n/SwiftGen+Strings.swift
  Packages/App/Sources/UILibrary/Resources/de.lproj/Localizable.strings
  Packages/App/Sources/UILibrary/Resources/el.lproj/Localizable.strings
  Packages/App/Sources/UILibrary/Resources/en.lproj/Localizable.strings
  Packages/App/Sources/UILibrary/Resources/es.lproj/Localizable.strings
  Packages/App/Sources/UILibrary/Resources/fr.lproj/Localizable.strings
  Packages/App/Sources/UILibrary/Resources/it.lproj/Localizable.strings
  Packages/App/Sources/UILibrary/Resources/nl.lproj/Localizable.strings
  Packages/App/Sources/UILibrary/Resources/pl.lproj/Localizable.strings
  Packages/App/Sources/UILibrary/Resources/pt.lproj/Localizable.strings
  Packages/App/Sources/UILibrary/Resources/ru.lproj/Localizable.strings
  Packages/App/Sources/UILibrary/Resources/sv.lproj/Localizable.strings
  Packages/App/Sources/UILibrary/Resources/uk.lproj/Localizable.strings
  Packages/App/Sources/UILibrary/Resources/zh-Hans.lproj/Localizable.strings
  Passepartout/Config.xcconfig
Labels: regression

#1083 Fix purchased features on Apple TV
  Packages/App/Sources/CommonLibrary/IAP/AppFeatureProviding+Products.swift
  Packages/App/Sources/CommonLibrary/IAP/IAPManager+Verify.swift
Labels: bug, refactoring

#1087 OpenVPN: Default gateway not set properly in some cases
  Packages/PassepartoutOpenVPNOpenSSL/Sources/PassepartoutOpenVPNOpenSSL/StandardOpenVPNParser+Builder.swift
  Packages/PassepartoutOpenVPNOpenSSL/Tests/PassepartoutOpenVPNOpenSSLTests/PushReplyTests.swift
Labels: regression

#1089 Do not require purchase for empty on-demand rules
  Packages/App/Sources/CommonLibrary/IAP/AppFeatureRequiring+Modules.swift
Labels: regression

#1090 Fix iCloud/TV sync not working with Advanced Data Protection
  Passepartout/App/Context/AppContext+Shared.swift
Labels: bug

#1094 OpenVPN: Resolve issues with long negotiations
  Packages/PassepartoutOpenVPNOpenSSL/Sources/PassepartoutOpenVPNOpenSSL/Internal/ControlChannel.swift
  Packages/PassepartoutOpenVPNOpenSSL/Sources/PassepartoutOpenVPNOpenSSL/Internal/DataChannel.swift
  Packages/PassepartoutOpenVPNOpenSSL/Sources/PassepartoutOpenVPNOpenSSL/Internal/Negotiator.swift
  Packages/PassepartoutOpenVPNOpenSSL/Sources/PassepartoutOpenVPNOpenSSL/Internal/OpenVPNSession+Acks.swift
  Packages/PassepartoutOpenVPNOpenSSL/Sources/PassepartoutOpenVPNOpenSSL/Internal/OpenVPNSession+Data.swift
  Packages/PassepartoutOpenVPNOpenSSL/Sources/PassepartoutOpenVPNOpenSSL/Internal/OpenVPNSession+Loop.swift
  Packages/PassepartoutOpenVPNOpenSSL/Sources/PassepartoutOpenVPNOpenSSL/Internal/OpenVPNSession+Negotiation.swift
  Packages/PassepartoutOpenVPNOpenSSL/Sources/PassepartoutOpenVPNOpenSSL/Internal/OpenVPNSession.swift
  Packages/PassepartoutOpenVPNOpenSSL/Sources/PassepartoutOpenVPNOpenSSL/Internal/OpenVPNUDPLink.swift
  Packages/PassepartoutOpenVPNOpenSSL/Sources/PassepartoutOpenVPNOpenSSL/Internal/XORProcessor.swift
Labels: regression, OpenVPN

#1095 OpenVPN: Restore and improve negotiation speed
  Packages/PassepartoutOpenVPNOpenSSL/Sources/PassepartoutOpenVPNOpenSSL/Internal/PushReply.swift
  Packages/PassepartoutOpenVPNOpenSSL/Sources/PassepartoutOpenVPNOpenSSL/StandardOpenVPNParser+Builder.swift
  Packages/PassepartoutOpenVPNOpenSSL/Sources/PassepartoutOpenVPNOpenSSL/StandardOpenVPNParser+Option.swift
  Packages/PassepartoutOpenVPNOpenSSL/Sources/PassepartoutOpenVPNOpenSSL/StandardOpenVPNParser.swift
  Packages/PassepartoutOpenVPNOpenSSL/Tests/PassepartoutOpenVPNOpenSSLTests/PushReplyTests.swift
  Packages/PassepartoutOpenVPNOpenSSL/Tests/PassepartoutOpenVPNOpenSSLTests/StandardOpenVPNParserTests.swift
Labels: enhancement, regression, OpenVPN

#1105 Do not show "Activating" when the tunnel is actually idle
  Packages/App/Sources/CommonLibrary/Business/ExtendedTunnel.swift
  Packages/App/Tests/CommonLibraryTests/Business/ExtendedTunnelTests.swift
Labels: bug

#1124 Hijack environment to run tests in PRs
  .github/workflows/test.yml
  .github/workflows/xcode_test.yml
  Packages/PassepartoutKit-Framework/Package.swift
Labels: bug, testing

#1123 tvOS: Override focus behavior to enforce button colors
  Packages/App/Sources/AppUIMain/Views/App/InstalledProfileView.swift
  Packages/App/Sources/AppUIMain/Views/App/ProfileContextMenu.swift
  Packages/App/Sources/AppUIMain/Views/App/ProfileRowView.swift
  Packages/App/Sources/AppUITV/Views/Profile/ActiveProfileView.swift
  Packages/App/Sources/AppUITV/Views/Profile/ProfileListView.swift
  Packages/App/Sources/UILibrary/Views/UI/TunnelToggleButton.swift
Labels: enhancement, tvOS

#1122 Fix Ukranian translations
  Packages/App/Sources/UILibrary/Resources/Credits.json
  Packages/App/Sources/UILibrary/Resources/uk.lproj/Localizable.strings
Labels: bug
